config/routes.rb
SampleApp::Application.routes.draw do

  post "periods/change", as: :change_periods

  resources :translinks
  resources :demandsites
  resources :supplysites
  resources :sites

  resources :products
  resources :machines
  resources :periods
  resources :product_periods
  resources :product_products
  resources :product_machines
  resources :machine_periods
  resources :users
  resources :topics
  resources :students
  resources :teams
  resources :student_topics
  resources :sessions, only: [:new, :create, :destroy]

  resources :assignments do
  collection {post :import}
  end
  resources :calculation_rooms
  resources :operating_rooms
  resources :patients
  resources :room_specialties
  resources :specialties
  resources :calculations
  resources :demand0s
  resources :demand1s
  resources :demand2s
  resources :stats

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/transport_start', to: 'static_pages#transport_start'
  match '/mlclsp_start', to: 'static_pages#mlclsp_start'
  match '/seminar_start', to: 'static_pages#seminar_start'
  match '/operationsplan_start', to: 'static_pages#operationsplan_start'

  match 'translinks/read_and_show_ofv', :to => 'translinks#read_and_show_ofv'
  match 'translinks/read_transportation_quantities', :to => 'translinks#read_transportation_quantities'
  match 'translinks/optimize', :to => 'translinks#optimize'
  match 'translinks/delete_transportation_quantities', :to => 'translinks#delete_transportation_quantities'

  match 'product_periods/read_and_show_ofv', :to => 'product_periods#read_and_show_ofv'
  match 'product_periods/read_optimization_results', :to => 'product_periods#read_optimization_results'
  match 'product_periods/optimize', :to => 'product_periods#optimize'
  match 'product_periods/delete_old_plan', :to => 'product_periods#delete_old_plan'
  match 'product_periods/show_index_page', :to => 'product_periods#show_index_page'

  match 'student_topics/read_and_show_ofv', :to => 'student_topics#read_and_show_ofv'
  match 'student_topics/read_assignments', :to => 'student_topics#read_assignments'
  match 'student_topics/optimize', :to => 'student_topics#optimize'
  match 'student_topics/erase_assignments', :to => 'student_topics#erase_assignments'

  match 'assignments/optimize', :to => 'assignments#optimize'
  match 'assignments/erase_assignments', :to => 'assignments#erase_assignments'
  match 'assignments/gamspfadassignment', :to =>'assignments#gamspfadassignment'
  match 'assignments/chart/:id', to: 'assignments#chart'
  match 'assignments/destroyid', :to => 'assignments#destroyid'

  match 'calculations/:id/aggregate', :to =>'calculations#aggregate'
  match 'calculations/pathtest', :to =>'assignments#test'
  match 'calculations/erase_calculations', :to => 'calculations#erase_calculations'
  
  match 'room_specialties/:id/assign', :to =>'room_specialties#assign'
  match 'room_specialties/:id/unassign', :to =>'room_specialties#unassign'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def start
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
#encoding: UTF-8

<% provide(:title, 'Über uns') %>
<h1>Über uns</h1>
<p>
  Im Kurs "Entwicklung von Anwendungssystemen" wird auf Basis des Rails-Tutorials von
  Michael Hartl die Entwicklung einer einfachen Web-Applikation zur betriebswirtschaftlichen
  Entscheidungsunterstützung behandelt. Dies eine der dabei erstellten Beispiel-Applikationen,
  die als Demonstrator für die Lösung unterschiedlicher Planungsprobleme des Operations Managements
  dient.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Kontakt') %>
<h1>Contact</h1>
<p>Andre Voss
</p>
<p>Jens Passlick<br />jenspasslick(-at-)googlemail.com</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Hilfe') %>
<h1>Hilfe</h1>
<p>
  Wenn Sie Hilfe brauchen, dann sollten Sie in die Vorlesung kommen!
  Für Hilfe mit Ruby on Rails empfehlen wir das
  <a href="http://railstutorial.org">Rails Tutorial</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Operations Management 1.0 (Demoanwendungen)</h1>


  <%= link_to "Melde Dich JETZT an!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/static_pages/mlclsp_start.html.erb
<% provide(:title, 'MLCLSP') %>
<h1>Losgrößenplanung mit dem MLCLSP</h1>
<p>
  Auf dieser Seite startet die Losgrößenplanung! <br> <br>

  <%= link_to "Verwaltung der Produkte!", products_path %><br>
  <%= link_to "Verwaltung der Maschinen!", machines_path %><br>
  <%= link_to "Verwaltung der Perioden!", periods_path %><br>
  <%= link_to "Verwaltung der Produkte-Produkte-Kombinationen!", product_products_path %><br>
  <%= link_to "Verwaltung der Produkte-Perioden-Kombinationen!", product_periods_path %><br>
  <%= link_to "Verwaltung der Produkte-Maschinen-Kombinationen!", product_machines_path %><br>
  <%= link_to "Verwaltung der Maschinen-Perioden-Kombinationen!", machine_periods_path %><br>

</p>

<br>


<% if signed_in? %>



    <p>

      Nach der Eingabe der Daten können wir nun endlich optimieren!

      <%= button_to "Lösche den Produktions- und Lagerplan", :controller => 'product_periods', :action => 'delete_old_plan' %>
      <%= button_to "Optimiere", :controller => 'product_periods', :action => 'optimize' %>
      <%= button_to "Lies die Ergebnisse ein", :controller => 'product_periods', :action => 'read_optimization_results' %>
      <%= button_to "Lies den Zielfunktionswert ein", :controller => 'product_periods', :action => 'read_and_show_ofv' %>

    </p>

<% end %>

app/views/static_pages/operationsplan_start.html.erb
<% provide(:title, 'Operationssaalplanung') %>
<h1>Operating Plan Management Center</h1>
<br>
 <h4> Here starts the block-schedule planning (for signed-in users):</h4>
<br />
  <% if signed_in? %>
<table class="buttontable">
	<tr>
		<td>
<span class="opbutton">
    <span class="opPlan"> <%= link_to "Show the latest operating plan!", assignments_path %></span><br>
    </span>
</td></tr>
</table>
<br>
<br>
	<h4>Data Management</h4>
    <br>
	
	<table id="start" class="display" >
  <thead>

  </thead>
<tbody>

  <tr>
       <td align="center"><%= link_to image_tag("glyphicons-530-list-alt.png", alt: "Specialty"), specialties_path %><br />
    	<%= link_to "Specialty management", specialties_path %></td>
    <td align="center"><%= link_to image_tag("glyphicons-496-bed.png", alt: "Operating Rooms"), operating_rooms_path %><br />
    	<%= link_to "Operating room management", operating_rooms_path %></td>
    <td align="center"><%= link_to image_tag("glyphicons-4-user.png", alt: "Patient"), patients_path %> <br />
      <%= link_to "Patient management", patients_path %> </td>
  </tr>
 </tbody>
</table>
	
      <br>
      <br>

  <% end %>

  <% if current_user.admin? %>

       <h2> Administrator Zone </h2>

       <h4> Manage operating plans </h4><br />
    <div class="center jumbotron"><%= link_to image_tag("glyphicons-158-show-thumbnails-with-lines.png", alt: "Calculations"), calculations_path %>
<br />
         <%= link_to "Calculations", calculations_path %><br></div>

  <% end %>

app/views/static_pages/seminar_start.html.erb
<% provide(:title, 'Seminarplanung') %>
<h1>Zuordnung von Studenten(teams) und Seminarthemen</h1>
<p>
  Auf dieser Seite startet (für angemeldete Nutzer) die Seminarplanung!    <br>     <br>

  <% if signed_in? %>

      <%= link_to "Hier geht es zur Verwaltung der Themen!", topics_path %><br>
      <%= link_to "Hier geht es zur Verwaltung der Studenten!", students_path %><br>
      <%= link_to "Hier geht es zur Verwaltung der Teams! (ohne Fkt!)", teams_path %><br>
      <%= link_to "Verwaltung der Studenten-Themen-Kombinationen!", student_topics_path %>
      </p>

      <br>


      <p>

      Nach der Eingabe der Daten können wir nun endlich optimieren!
      <%= button_to "Lösche die Zuordnung", :controller => 'student_topics', :action => 'erase_assignments' %>
      <%= button_to "Optimiere", :controller => 'student_topics', :action => 'optimize' %>
      <%= button_to "Lies die Zuordnung ein", :controller => 'student_topics', :action => 'read_assignments' %>
      <%= button_to "Lies den Zielfunktionswert ein", :controller => 'student_topics', :action => 'read_and_show_ofv' %>
      </p>

  <% end %>

app/views/static_pages/transport_start.html.erb
<% provide(:title, 'Transportplanung') %>
<h1>Klassisches Transportmodell</h1>
<p>
Auf dieser Seite startet die Transportplanung!    <br>     <br>

<%= link_to "Hier geht es zur Verwaltung der Orte!", sites_path %><br>
<%= link_to "Hier geht es zur Verwaltung der Angebotsdaten!", supplysites_path %><br>
<%= link_to "Hier geht es zur Verwaltung der Nachfragedaten!", demandsites_path %><br>
<%= link_to "Hier geht es zur Verwaltung der Transportrelationen!", translinks_path %><br>
</p>

<br>


<% if signed_in? %>



<p>

Nach der Eingabe der Daten können wir nun endlich optimieren!

  <%= button_to "Lösche Transportmengen", :controller => 'translinks', :action =>  'delete_transportation_quantities'  %>
  <%= button_to "Optimiere", :controller => 'translinks', :action =>  'optimize'  %>
  <%= button_to "Lies die Transportmengen ein", :controller => 'translinks', :action =>  'read_transportation_quantities'  %>
  <%= button_to "Lies den Zielfunktionswert ein", :controller => 'translinks', :action =>  'read_and_show_ofv'  %>

</p>

<% end %>