config/routes.rb
SampleApp::Application.routes.draw do

  post "periods/change", as: :change_periods

  resources :translinks
  resources :demandsites
  resources :supplysites
  resources :sites

  resources :products
  resources :machines
  resources :periods
  resources :product_periods
  resources :product_products
  resources :product_machines
  resources :machine_periods
  resources :users
  resources :topics
  resources :students
  resources :teams
  resources :student_topics
  resources :sessions, only: [:new, :create, :destroy]

  resources :assignments do
  collection {post :import}
  end
  resources :calculation_rooms
  resources :operating_rooms
  resources :patients
  resources :room_specialties
  resources :specialties
  resources :calculations
  resources :demand0s
  resources :demand1s
  resources :demand2s
  resources :stats

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/transport_start', to: 'static_pages#transport_start'
  match '/mlclsp_start', to: 'static_pages#mlclsp_start'
  match '/seminar_start', to: 'static_pages#seminar_start'
  match '/operationsplan_start', to: 'static_pages#operationsplan_start'

  match 'translinks/read_and_show_ofv', :to => 'translinks#read_and_show_ofv'
  match 'translinks/read_transportation_quantities', :to => 'translinks#read_transportation_quantities'
  match 'translinks/optimize', :to => 'translinks#optimize'
  match 'translinks/delete_transportation_quantities', :to => 'translinks#delete_transportation_quantities'

  match 'product_periods/read_and_show_ofv', :to => 'product_periods#read_and_show_ofv'
  match 'product_periods/read_optimization_results', :to => 'product_periods#read_optimization_results'
  match 'product_periods/optimize', :to => 'product_periods#optimize'
  match 'product_periods/delete_old_plan', :to => 'product_periods#delete_old_plan'
  match 'product_periods/show_index_page', :to => 'product_periods#show_index_page'

  match 'student_topics/read_and_show_ofv', :to => 'student_topics#read_and_show_ofv'
  match 'student_topics/read_assignments', :to => 'student_topics#read_assignments'
  match 'student_topics/optimize', :to => 'student_topics#optimize'
  match 'student_topics/erase_assignments', :to => 'student_topics#erase_assignments'

  match 'assignments/optimize', :to => 'assignments#optimize'
  match 'assignments/erase_assignments', :to => 'assignments#erase_assignments'
  match 'assignments/gamspfadassignment', :to =>'assignments#gamspfadassignment'
  match 'assignments/chart/:id', to: 'assignments#chart'
  match 'assignments/destroyid', :to => 'assignments#destroyid'

  match 'calculations/:id/aggregate', :to =>'calculations#aggregate'
  match 'calculations/pathtest', :to =>'assignments#test'
  match 'calculations/erase_calculations', :to => 'calculations#erase_calculations'
  
  match 'room_specialties/:id/assign', :to =>'room_specialties#assign'
  match 'room_specialties/:id/unassign', :to =>'room_specialties#unassign'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :shortcode, :title

  has_many :student_topics, :dependent => :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  respond_to :html, :json
  before_filter :signed_in_user
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Thema wurde erfolgreich angelegt!' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: 'Thema wurde erfolgreich aktualisiert.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end
end


private

def signed_in_user
  unless signed_in?
    store_location
    redirect_to signin_path, notice: "Bitte melden Sie sich an."
  end
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Titelcode' %><br />
    <%= f.text_field :shortcode %>
  </div>
  <div class="field">
    <%= f.label 'Titel' %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit 'Thema anlegen oder aktualisieren' %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Thema ändern</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @topic %> |
<%= link_to 'Zurück', topics_path %>

app/views/topics/index.html.erb
<h1>Übersicht der Themen</h1>
<table  id="topics" class="display">
  <thead>
  <tr>
    <th>Titelcode</th>
    <th>Titel des Themas</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>

  <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.shortcode %></td>
        <td><%= topic.title %></td>
        <td><%= link_to 'Zeigen', topic %></td>
        <td><%= link_to 'Ändern', edit_topic_path(topic) %></td>
        <td><%= link_to 'Löschen', topic, method: :delete, data: {confirm: 'Sind Sie sicher?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'Neues Thema anlegen', new_topic_path %><br>  <br>
<%= link_to 'Zurück zur Seminarplanung', seminar_start_path %>

app/views/topics/new.html.erb
<h1>Neues Thema</h1>

<%= render 'form' %>

<%= link_to 'Zurück', topics_path %>

app/views/topics/show.html.erb
<!--<p id="notice"><%= notice %></p> -->


<p>
  <b>Titelcode:</b>
  <%= @topic.shortcode %>
</p>

<p>
  <b>Titel:</b>
  <%= best_in_place @topic, :title %>
</p>


<%= link_to 'Ändern', edit_topic_path(@topic) %> |
<%= link_to 'Zurück', topics_path %>