config/routes.rb
SampleApp::Application.routes.draw do

  post "periods/change", as: :change_periods

  resources :translinks
  resources :demandsites
  resources :supplysites
  resources :sites

  resources :products
  resources :machines
  resources :periods
  resources :product_periods
  resources :product_products
  resources :product_machines
  resources :machine_periods
  resources :users
  resources :topics
  resources :students
  resources :teams
  resources :student_topics
  resources :sessions, only: [:new, :create, :destroy]

  resources :assignments do
  collection {post :import}
  end
  resources :calculation_rooms
  resources :operating_rooms
  resources :patients
  resources :room_specialties
  resources :specialties
  resources :calculations
  resources :demand0s
  resources :demand1s
  resources :demand2s
  resources :stats

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/transport_start', to: 'static_pages#transport_start'
  match '/mlclsp_start', to: 'static_pages#mlclsp_start'
  match '/seminar_start', to: 'static_pages#seminar_start'
  match '/operationsplan_start', to: 'static_pages#operationsplan_start'

  match 'translinks/read_and_show_ofv', :to => 'translinks#read_and_show_ofv'
  match 'translinks/read_transportation_quantities', :to => 'translinks#read_transportation_quantities'
  match 'translinks/optimize', :to => 'translinks#optimize'
  match 'translinks/delete_transportation_quantities', :to => 'translinks#delete_transportation_quantities'

  match 'product_periods/read_and_show_ofv', :to => 'product_periods#read_and_show_ofv'
  match 'product_periods/read_optimization_results', :to => 'product_periods#read_optimization_results'
  match 'product_periods/optimize', :to => 'product_periods#optimize'
  match 'product_periods/delete_old_plan', :to => 'product_periods#delete_old_plan'
  match 'product_periods/show_index_page', :to => 'product_periods#show_index_page'

  match 'student_topics/read_and_show_ofv', :to => 'student_topics#read_and_show_ofv'
  match 'student_topics/read_assignments', :to => 'student_topics#read_assignments'
  match 'student_topics/optimize', :to => 'student_topics#optimize'
  match 'student_topics/erase_assignments', :to => 'student_topics#erase_assignments'

  match 'assignments/optimize', :to => 'assignments#optimize'
  match 'assignments/erase_assignments', :to => 'assignments#erase_assignments'
  match 'assignments/gamspfadassignment', :to =>'assignments#gamspfadassignment'
  match 'assignments/chart/:id', to: 'assignments#chart'
  match 'assignments/destroyid', :to => 'assignments#destroyid'

  match 'calculations/:id/aggregate', :to =>'calculations#aggregate'
  match 'calculations/pathtest', :to =>'assignments#test'
  match 'calculations/erase_calculations', :to => 'calculations#erase_calculations'
  
  match 'room_specialties/:id/assign', :to =>'room_specialties#assign'
  match 'room_specialties/:id/unassign', :to =>'room_specialties#unassign'

end

app/models/supplysite.rb
# == Schema Information
#
# Table name: supplysites
#
#  id              :integer          not null, primary key
#  site_id         :integer
#  supply_quantity :float
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Supplysite < ActiveRecord::Base
  attr_accessible :supply_quantity, :site_id
  validates :supply_quantity, :numericality => { :greater_than => 0}


  belongs_to :site
  has_many :translinks, :dependent => :destroy
  accepts_nested_attributes_for :translinks


  def supplysite_codename
    self.site.codename
  end
end

app/controllers/supplysites_controller.rb
class SupplysitesController < ApplicationController

  before_filter :signed_in_user


  # GET /supplysites
  # GET /supplysites.json
  def index
    @supplysites = Supplysite.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @supplysites }
    end
  end

  # GET /supplysites/1
  # GET /supplysites/1.json
  def show
    @supplysite = Supplysite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @supplysite }
    end
  end

  # GET /supplysites/new
  # GET /supplysites/new.json
  def new
    @supplysite = Supplysite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @supplysite }
    end
  end

  # GET /supplysites/1/edit
  def edit
    @supplysite = Supplysite.find(params[:id])
  end

  # POST /supplysites
  # POST /supplysites.json
  def create
    @supplysite = Supplysite.new(params[:supplysite])

    respond_to do |format|
      if @supplysite.save
        format.html { redirect_to @supplysite, notice: 'Angebotsort wurde erfolgreich angelegt.' }
        format.json { render json: @supplysite, status: :created, location: @supplysite }
      else
        format.html { render action: "new" }
        format.json { render json: @supplysite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /supplysites/1
  # PUT /supplysites/1.json
  def update
    @supplysite = Supplysite.find(params[:id])

    respond_to do |format|
      if @supplysite.update_attributes(params[:supplysite])
        format.html { redirect_to @supplysite, notice: 'Angebotsort wurde erfolgreich aktualisiert.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @supplysite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplysites/1
  # DELETE /supplysites/1.json
  def destroy
    @supplysite = Supplysite.find(params[:id])
    @supplysite.destroy

    respond_to do |format|
      format.html { redirect_to supplysites_url }
      format.json { head :no_content }
    end
  end
end


private

def signed_in_user
  unless signed_in?
    store_location
    redirect_to signin_path, notice: "Bitte melden Sie sich an."
  end
end

app/helpers/supplysites_helper.rb
module SupplysitesHelper
end

app/views/supplysites/_form.html.erb
<%= form_for(@supplysite) do |f| %>
  <% if @supplysite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supplysite.errors.count, "error") %> prohibited this supplysite from being saved:</h2>

      <ul>
      <% @supplysite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Code auswählen' %><br />
    <%= f.collection_select :site_id, Site.all, :id, :codename %>
  </div>
  <div class="field">
    <%= f.label 'Angebotsmenge eingeben' %><br />
    <%= f.text_field :supply_quantity %>
  </div>
  <div class="actions">
    <%= f.submit "Angebotsort anlegen oder aktualisieren" %>
  </div>
<% end %>

app/views/supplysites/edit.html.erb
<h1>Angebotsort ändern</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @supplysite %> |
<%= link_to 'Zurück', supplysites_path %>

app/views/supplysites/index.html.erb
<h1>Daten der Angebotsorte</h1>

<table class="table">
  <tr>
    <th>Code</th>
    <th>Ort</th>
    <th>Angebotsmenge</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @supplysites.each do |supplysite| %>
  <tr>
    <td><%= supplysite.site.codename %></td>
    <td><%= supplysite.site.name %></td>
    <td><%= supplysite.supply_quantity %></td>
    <td><%= link_to 'Ändern', edit_supplysite_path(supplysite) %></td>
    <td><%= link_to 'Löschen', supplysite, method: :delete, data: { confirm: 'Sind Sie sicher?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Neuen Angebotsort anlegen', new_supplysite_path %><br>  <br>
<%= link_to 'Zurück zur Transportplanung', transport_start_path %>

app/views/supplysites/new.html.erb
<h1>Neuer Angebotsort</h1>

<%= render 'form' %>

<%= link_to 'Zurück', supplysites_path %>

app/views/supplysites/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<p>
  <b>Angebotsort:</b>
  <%= @supplysite.site.name %>
</p>

<p>
  <b>Angebotsmenge:</b>
  <%= @supplysite.supply_quantity %>
</p>


<%= link_to 'Ändern', edit_supplysite_path(@supplysite) %> |
<%= link_to 'Zurück', supplysites_path %>